unzip /mmfs1/gscratch/amath/dob1998/emissions_forecasting/data/zip/IOT_pxp/IOT_1995_pxp.zip -d /mmfs1/gscratch/amath/dob1998/emissions_forecasting/data/IOT_pxp/
unzip /mmfs1/gscratch/amath/dob1998/emissions_forecasting/data/zip/IOT_pxp/IOT_1996_pxp.zip -d /mmfs1/gscratch/amath/dob1998/emissions_forecasting/data/IOT_pxp/
unzip /mmfs1/gscratch/amath/dob1998/emissions_forecasting/data/zip/IOT_pxp/IOT_1997_pxp.zip -d /mmfs1/gscratch/amath/dob1998/emissions_forecasting/data/IOT_pxp/
unzip /mmfs1/gscratch/amath/dob1998/emissions_forecasting/data/zip/IOT_pxp/IOT_1998_pxp.zip -d /mmfs1/gscratch/amath/dob1998/emissions_forecasting/data/IOT_pxp/
unzip /mmfs1/gscratch/amath/dob1998/emissions_forecasting/data/zip/IOT_pxp/IOT_1999_pxp.zip -d /mmfs1/gscratch/amath/dob1998/emissions_forecasting/data/IOT_pxp/
unzip /mmfs1/gscratch/amath/dob1998/emissions_forecasting/data/zip/IOT_pxp/IOT_2000_pxp.zip -d /mmfs1/gscratch/amath/dob1998/emissions_forecasting/data/IOT_pxp/
unzip /mmfs1/gscratch/amath/dob1998/emissions_forecasting/data/zip/IOT_pxp/IOT_2001_pxp.zip -d /mmfs1/gscratch/amath/dob1998/emissions_forecasting/data/IOT_pxp/
unzip /mmfs1/gscratch/amath/dob1998/emissions_forecasting/data/zip/IOT_pxp/IOT_2002_pxp.zip -d /mmfs1/gscratch/amath/dob1998/emissions_forecasting/data/IOT_pxp/
unzip /mmfs1/gscratch/amath/dob1998/emissions_forecasting/data/zip/IOT_pxp/IOT_2003_pxp.zip -d /mmfs1/gscratch/amath/dob1998/emissions_forecasting/data/IOT_pxp/
unzip /mmfs1/gscratch/amath/dob1998/emissions_forecasting/data/zip/IOT_pxp/IOT_2004_pxp.zip -d /mmfs1/gscratch/amath/dob1998/emissions_forecasting/data/IOT_pxp/
unzip /mmfs1/gscratch/amath/dob1998/emissions_forecasting/data/zip/IOT_pxp/IOT_2005_pxp.zip -d /mmfs1/gscratch/amath/dob1998/emissions_forecasting/data/IOT_pxp/
unzip /mmfs1/gscratch/amath/dob1998/emissions_forecasting/data/zip/IOT_pxp/IOT_2006_pxp.zip -d /mmfs1/gscratch/amath/dob1998/emissions_forecasting/data/IOT_pxp/
unzip /mmfs1/gscratch/amath/dob1998/emissions_forecasting/data/zip/IOT_pxp/IOT_2007_pxp.zip -d /mmfs1/gscratch/amath/dob1998/emissions_forecasting/data/IOT_pxp/
unzip /mmfs1/gscratch/amath/dob1998/emissions_forecasting/data/zip/IOT_pxp/IOT_2008_pxp.zip -d /mmfs1/gscratch/amath/dob1998/emissions_forecasting/data/IOT_pxp/
unzip /mmfs1/gscratch/amath/dob1998/emissions_forecasting/data/zip/IOT_pxp/IOT_2009_pxp.zip -d /mmfs1/gscratch/amath/dob1998/emissions_forecasting/data/IOT_pxp/
unzip /mmfs1/gscratch/amath/dob1998/emissions_forecasting/data/zip/IOT_pxp/IOT_2010_pxp.zip -d /mmfs1/gscratch/amath/dob1998/emissions_forecasting/data/IOT_pxp/
unzip /mmfs1/gscratch/amath/dob1998/emissions_forecasting/data/zip/IOT_pxp/IOT_2011_pxp.zip -d /mmfs1/gscratch/amath/dob1998/emissions_forecasting/data/IOT_pxp/
unzip /mmfs1/gscratch/amath/dob1998/emissions_forecasting/data/zip/IOT_pxp/IOT_2012_pxp.zip -d /mmfs1/gscratch/amath/dob1998/emissions_forecasting/data/IOT_pxp/
unzip /mmfs1/gscratch/amath/dob1998/emissions_forecasting/data/zip/IOT_pxp/IOT_2013_pxp.zip -d /mmfs1/gscratch/amath/dob1998/emissions_forecasting/data/IOT_pxp/
unzip /mmfs1/gscratch/amath/dob1998/emissions_forecasting/data/zip/IOT_pxp/IOT_2014_pxp.zip -d /mmfs1/gscratch/amath/dob1998/emissions_forecasting/data/IOT_pxp/
unzip /mmfs1/gscratch/amath/dob1998/emissions_forecasting/data/zip/IOT_pxp/IOT_2015_pxp.zip -d /mmfs1/gscratch/amath/dob1998/emissions_forecasting/data/IOT_pxp/
unzip /mmfs1/gscratch/amath/dob1998/emissions_forecasting/data/zip/IOT_pxp/IOT_2016_pxp.zip -d /mmfs1/gscratch/amath/dob1998/emissions_forecasting/data/IOT_pxp/
unzip /mmfs1/gscratch/amath/dob1998/emissions_forecasting/data/zip/IOT_pxp/IOT_2017_pxp.zip -d /mmfs1/gscratch/amath/dob1998/emissions_forecasting/data/IOT_pxp/
unzip /mmfs1/gscratch/amath/dob1998/emissions_forecasting/data/zip/IOT_pxp/IOT_2018_pxp.zip -d /mmfs1/gscratch/amath/dob1998/emissions_forecasting/data/IOT_pxp/
unzip /mmfs1/gscratch/amath/dob1998/emissions_forecasting/data/zip/IOT_pxp/IOT_2019_pxp.zip -d /mmfs1/gscratch/amath/dob1998/emissions_forecasting/data/IOT_pxp/
unzip /mmfs1/gscratch/amath/dob1998/emissions_forecasting/data/zip/IOT_pxp/IOT_2020_pxp.zip -d /mmfs1/gscratch/amath/dob1998/emissions_forecasting/data/IOT_pxp/
unzip /mmfs1/gscratch/amath/dob1998/emissions_forecasting/data/zip/IOT_pxp/IOT_2021_pxp.zip -d /mmfs1/gscratch/amath/dob1998/emissions_forecasting/data/IOT_pxp/
unzip /mmfs1/gscratch/amath/dob1998/emissions_forecasting/data/zip/IOT_pxp/IOT_2022_pxp.zip -d /mmfs1/gscratch/amath/dob1998/emissions_forecasting/data/IOT_pxp/
